---
services:

  # Backend API Container
  api:
    image: ghcr.io/sankalpx5/expense-tracker-api:latest # pulls latest api image from ghcr.io
    container_name: api
    restart: unless-stopped # restart policy
    ports:
    - 5000:5000
    env_file:
      - .env
    healthcheck:
      # healthcheck on /health route of api using in built tools
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/5000 && echo -e "GET /health HTTP/1.1\r\nhost: 127.0.0.1:5000\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "ok"' 
      interval: 20s
      timeout: 10s
      retries: 5