name: OCR build and push ci

on:
  push:
    branches:
      - "main"
    paths:
      - "services/receipt-ocr/**"
      - ".github/workflows/build-ocr.yml"

env:
  IMAGE_NAME: receipt-ocr

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./services/receipt-ocr
          file: ./services/receipt-ocr/Dockerfile.local
          push: true
          tags: ghcr.io/sankalpx5/${{ env.IMAGE_NAME }}:latest

      - name: Log out from Docker Hub
        run: docker logout
